name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: create .devN build date
      if: github.event_name != 'release'
      run: TZ='America/New_York' date '+%Y%m%d%H%M' > dev-build.txt

    - name: build it
      run: |
        python3 -m pip install build twine
        # called without --wheel and --sdist, build somehow misses the build date in the wheel
        python3 -m build --wheel
        python3 -m build --sdist

    - name: Upload test package
      if: github.event_name != 'release'
      env:
        TWINE_REPOSITORY: testpypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*

    - name: Release upload
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*
