name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        python_version: ['3.12']
#        os: ['ubuntu-latest', 'macos-13']
        os: ['ubuntu-latest']
        include:
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_34_x86_64 # https://github.com/pypa/manylinux
            upload_source: true   # only one need upload sources...

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build --wheel

    - name: run auditwheel for manylinux
      if: matrix.container != ''
      run: |
        auditwheel repair dist/*.whl
        rm -f dist/*.whl
        mv wheelhouse/*.whl dist/

    - name: build source dist
      if: matrix.upload_source
      run: python3 -m build --sdist

    - name: Upload test package
      if: github.event_name != 'release'
      env:
        TWINE_REPOSITORY: testpypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*

    - name: Release upload
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*
