name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  pick-devN:
    name: create .devN build date coordinated across all matrix jobs
    runs-on: ubuntu-latest
    steps:
      - run: TZ='America/New_York' date '+%Y%m%d%H%M' > dev-build.txt

      - uses: actions/upload-artifact@v4
        with:
          name: devN
          path: dev-build.txt

  release:
    needs: pick-devN
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        python_version: ['3.12', '3.13']
        os: ['ubuntu-latest', 'macos-13', 'windows-latest']
        include:
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_34_x86_64 # https://github.com/pypa/manylinux
#            upload_source: true   # only one need upload sources...

    steps:
    - uses: actions/checkout@v4

    - name: get coordinated .devN
      if: github.event_name != 'release'
      uses: actions/download-artifact@v4
      with:
        name: devN

    - name: set up python (non-container)
      if: matrix.container == ''
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: set up python (container)
      if: matrix.container != ''
      run: |
        PYV=`echo "${{ matrix.python_version }}" | tr -d "."`; ls -d -1 /opt/python/cp$PYV*/bin | head -n 1 >> $GITHUB_PATH
        cat $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build --wheel

    - name: run auditwheel for manylinux
      if: matrix.container != ''
      run: |
        auditwheel repair dist/*.whl
        rm -f dist/*.whl
        mv wheelhouse/*.whl dist/

    - name: build source dist
      if: matrix.upload_source
      run: python3 -m build --sdist

    - name: Upload test package
      if: github.event_name != 'release'
      env:
        TWINE_REPOSITORY: testpypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*

    - name: Release upload
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --verbose dist/*
